theme: jekyll-theme-tactile
title: DraperDanMan's Blog
description: Posts about Gamedev, C#, C++, and my custom Data-Oriented Engine called Carbon.

# --- blog info --- #

author:
  name: Daniel Draper

social-network-links:
  rss: true
  github: draperdanman
  twitter: draperdanman
  reddit: draperdanman
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
url-blog: "DraperDanMan.github.io"

# -- Navigation -- #
navbar-links:
  Tags: "tags"
  About: "about"

# --- CSS options --- #

navbar-col: "#FEFEFE"
navbar-text-col: "#101010"
navbar-children-col: "#FAFAFA"
page-col: "#FFFFFF"
link-col: "#2A7AE2"
hover-col: "#111"
footer-col: "#FEFEFE"
footer-text-col: "#101010"
footer-link-col: "#404040"

excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "Australia/Melbourne"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap